using Content.Client._FS19.UserInterface.Systems.WhitelistAdd;
using Content.Shared._FS19.WhitelistAdd;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Robust.Shared.Player;
using System;
using System.Runtime.CompilerServices;

namespace Content.Client._FS19.UserInterface.Systems.WhitelistAdd.UI;

[GenerateTypedNameReferences]
public sealed partial class WhitelistAddMenu : DefaultWindow
{
    private readonly WhitelistAddUIController _controller;
    public event Action<WhitelistAddMessage>? OnWhitelistAddSent;
    public WhitelistAddMenu()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => OnConfirmButtonPressed();
        _controller = UserInterfaceManager.GetUIController<WhitelistAddUIController>();
    }


    private void OnConfirmButtonPressed()
    {
        string invitee = UsernameEdit.Text;

        _controller.OnWhitelistAddSent(invitee);
    }
}
