using Content.Client._FS19.UserInterface.Systems.WhitelistAdd;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._FS19.UserInterface.Systems.WhitelistAdd.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class WhitelistAddMenu : DefaultWindow
    {
        public WhitelistAddMenu()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
